### ISSUE TITLE
Installing fzf with lazy.nvim

### ISSUE THREAD

**Issue by taeyoungson** [wookayin/dotfiles#47] opened 2023-09-27 06:20 UTC
Hi! 
Thanks in advance for sharing this wonderful configurations.

I have been using this repo for long time, and since some point I found out that junegunn/fzf plugin is not automatically installed at "$HOME/.fzf" folder. 

I suspect this behavior is related to installing mechanism of lazy.nvim, similar issue is raised in this [link](https://www.reddit.com/r/neovim/comments/13utr4w/install_fzf_including_shell_completion_with/?rdt=61512) and it suggests leaving out "dir=~/.fzf" part.

Leaving it out and adjust /.local/bin/fzf to point ~/.vim/plugged/fzf/bin/fzf resolves problem, but I wonder if there's a way to automate this process using lazy nvim (like through editing nvim/lua/plugins/ui.lua)

Thanks again for your effort.

**Comment by wookayin** [comment] 2023-09-28 22:26
Hi @taeyoungson, thanks so much for using my dotfiles!

I wasn't aware of this bug because it has been a while since I tried a fresh installation. This is actually an unintended behavior, lazy.nvim does not install on non-standard directory when `dir` is specified. The directory `~/.fzf` was assumed to be installed by vim plugin manager (previously vim-plug) but since the behavior of lazy.nvim and vim-plug are different, I will have to improve the installation process of fzf. Since fzf is also used as a huge part of zsh setup, **I do not prefer installing fzf into `~/.vim/plugged`.**

Once fzf is installed for the fresh checkout, it can be updated by lazy.nvim.

BTW I will merge #46 very soon which removes all the use of `fzf` as a vim plugin. So after this merged vim will be still useable even if `~/.fzf` does not exist, but I can fix this unintended behavior nevertheless.

**Closed** 2023-09-28 22:50 UTC
Labels: bug
